jQuery(function($){
$("#show_all").click(function(){
        $("#show_all").hide();
$("#show_3").show();
    $("#all_reviews").show();
    $("#3_reviews").hide();
    });
    $("#show_3").click(function(){
        $("#show_3").hide();
$("#show_all").show();
        $("#all_reviews").hide();
        $("#3_reviews").show();
    });
});
